/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "secondary-container": "#dfe0e0",
        "surface-container": "#e5eeff",
        "inverse-primary": "#b3c5ff",
        "secondary-fixed": "#e2e2e2",
        "on-tertiary-fixed": "#390c00",
        "on-primary-fixed-variant": "#003fa4",
        "on-tertiary-fixed-variant": "#832600",
        "outline": "#727687",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#454747",
        "primary": "#0050cb",
        "primary-fixed": "#dae1ff",
        "inverse-surface": "#213145",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary": "#a33200",
        "tertiary-fixed": "#ffdbd0",
        "on-surface": "#0b1c30",
        "surface-container-high": "#dce9ff",
        "on-secondary-container": "#616363",
        "inverse-on-surface": "#eaf1ff",
        "primary-container": "#0066ff",
        "secondary-fixed-dim": "#c6c6c7",
        "outline-variant": "#c2c6d8",
        "background": "#f8f9ff",
        "on-primary-fixed": "#001849",
        "primary-fixed-dim": "#b3c5ff",
        "on-error-container": "#93000a",
        "surface-variant": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#1a1c1c",
        "tertiary-fixed-dim": "#ffb59d",
        "on-surface-variant": "#424656",
        "on-tertiary-container": "#fff6f4",
        "error": "#ba1a1a",
        "on-background": "#0b1c30",
        "surface-tint": "#0054d6",
        "secondary": "#5d5f5f",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#cc4204",
        "on-primary": "#ffffff",
        "on-primary-container": "#f8f7ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sidebar_width": "280px",
        "margin_mobile": "16px",
        "stack_sm": "8px",
        "stack_lg": "32px",
        "container_max_width": "1440px",
        "gutter": "24px",
        "margin_desktop": "40px",
        "stack_md": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "code-sm": ["Geist", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        "geist": ["Geist", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "code-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
